Remove from gRPC:IClientConfig:ISimplifiedClientConfig unused type parameter
join-com/grpc pull request #32
Opened 2021-08-06 08:31 UTC by Alexsey

2021-08-06 08:40 UTC, castarco commented on packages/grpc/src/__tests__/generated/foo/Foo.ts
> -      config: joinGRPC.ISimplifiedClientConfig<ITestSvcServiceImplementation>,
this is generated code, shouldn't be modified by hand.

2021-08-06 08:41 UTC, castarco requested changes
This change should be better justified, and described.

The distinction between the two interfaces (the simplified one and the "base one") is there for a reason; depending on at what level of abstraction we are operating.

2021-08-06 08:55 UTC, castarco commented on packages/grpc/src/interfaces/IClientConfig.ts
> +}
Please don't change the order of the declarations, it makes reviewing more complicated, and it does not provide extra value.

2021-08-06 08:57 UTC, castarco commented on packages/grpc/src/interfaces/IClientConfig.ts
> +export interface ISimplifiedClientConfig {
the type parameter should be kept as optional for backwards compatibility with the generator.

2021-08-06 10:25 UTC, castarco commented on packages/grpc/src/interfaces/IClientConfig.ts
> +  address: string | (IgnoreMe & never) // the same as `string`. Just need to mention IgnoreMe for the compiler to be happy
Instead of doing that, we can prefix `IgnoreMe` with `_` -> `_IgnoreMe`, and add an annotation for eslint to accept the useless type parameter. I think it would be cleaner.

2021-08-06 10:28 UTC, Alexsey commented on packages/grpc/src/interfaces/IClientConfig.ts
> +  address: string | (IgnoreMe & never) // the same as `string`. Just need to mention IgnoreMe for the compiler to be happy
Yes, this is definitely the right way to do it. Done!

2021-08-06 10:29 UTC, castarco approved these changes

2021-08-06 10:29 UTC, merged

2022-01-18 08:02 UTC, join-admin commented
:tada: This PR is included in version @join-private/grpc-v1.0.0-alpha.1 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@join-private/grpc/v/1.0.0-alpha.1)
- [GitHub release](https://github.com/join-com/grpc/releases/tag/%40join-private/grpc-v1.0.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: